export type ProviderStatus='PENDING'|'AUTHORIZED'|'SUSPENDED'|'EXPIRED'|'REJECTED';
export type UserRole='SUPER_ADMIN'|'ADMIN'|'SERVICE_MANAGER'|'PROVIDER'|'BUSINESS_OWNER'|'RESIDENT';
export type RequestStatus='SUBMITTED'|'UNDER_REVIEW'|'PROVIDER_ASSIGNED'|'PROVIDER_ACCEPTED'|'ON_THE_WAY'|'SERVICE_STARTED'|'SERVICE_COMPLETED'|'RESIDENT_CONFIRMATION'|'COMPLETED'|'CANCELLED';
